### ISSUE TITLE
xml format issue

### ISSUE THREAD

**Issue by manantwar** [TwilioDevEd/client-quickstart-csharp#3]
Hi, Im using the view page of project to place a call. as shown below

![image](https://user-images.githubusercontent.com/6465572/36841265-cbf54f66-1d6d-11e8-9e43-88d3d8bf29c0.png)

However my call is getting dropped with schema validation error. 
![image](https://user-images.githubusercontent.com/6465572/36841307-eca97674-1d6d-11e8-9713-329625327c4e.png)

Looks like html of page is sent as body. shouldn't this be twiml xml? what am i missing here?

**Comment by jefflinwood** [comment]
Hi,

Sorry for not getting back to you before with this error! The problem is that the URL for the TwiML app needs to have the /voice path - so something like https://a2b2.ngrok.io/voice

Thanks,
Jeff
